#!/bin/bash 
#!
# @ job_name = MPI_config
# standard output file  
# @ output = $(job_name).$(jobid)
# standard error file
# @ error =  $(job_name).$(jobid)
# job type
# @ job_type = parallel
# Number of procs 
# @ total_tasks = NPROCS
# time
# @ wall_clock_limit = 00:59:00
# @ queue

#
# Test specific settings. Do not hand edit these lines; the fcm_job.sh script will set these
# (via sed operating on this template job file). 
#
  OCEANCORES=NPROCS
  export SETTE_DIR=DEF_SETTE_DIR

###############################################################
#
# set up mpp computing environment
#
# Local settings for machine IBM Power6 (VARGAS at IDRIS France)
#
#export MPIRUN="poe -procs $OCEANCORES"
#export MPIRUN="mpirun"
export MPIRUN="poe"

#
# load sette functions (only post_test_tidyup needed)
#
  . ${SETTE_DIR}/all_functions.sh
#

# Don't remove neither change the following line
# BODY

#
# These variables are needed by post_test_tidyup function in all_functions.sh
#
  export EXE_DIR=DEF_EXE_DIR
  export INPUT_DIR=DEF_INPUT_DIR
  export CONFIG_DIR=DEF_CONFIG_DIR
  export TOOLS_DIR=DEF_TOOLS_DIR
  export NEMO_VALIDATION_DIR=DEF_NEMO_VALIDATION
  export NEW_CONF=DEF_NEW_CONF
  export CMP_NAM=DEF_CMP_NAM
  export TEST_NAME=DEF_TEST_NAME
#
# end of set up
###############################################################
#
# change to the working directory 
#
cd ${EXE_DIR}

  echo Running on host `hostname`
  echo Time is `date`
  echo Directory is `pwd`
# 
#  Run the parallel MPI executable 
#
#  echo "Running time ${MPIRUN} ./nemo"
#
  if [ MPI_FLAG == "yes" ]; then
     echo "Running time ${MPIRUN} -np $OCEANCORES ./nemo"
     #time ${MPIRUN} -np $OCEANCORES ./nemo
     time ${MPIRUN} ./nemo -procs $OCEANCORES
  else
     echo "Running time ./nemo"
     time ./nemo
  fi

#
  post_test_tidyup

# END_BODY
# Don't remove neither change the previous line


  exit
