#!/bin/bash

myhostname=`hostname`

if [[ $myhostname = irene* ]]
then
  export xios_machine_name=irene
elif [[ $myhostname = jean-zay* ]]
then
  export xios_machine_name=jeanzay
fi 

source ./ENV/${xios_machine_name}.env
export PATH=`pwd`/TOOLS:$PATH 
