#!/bin/bash
FORGE_DIR=/ipsl/forge/projets/ioserver/XIOS_TEST_SUITE
forge_IP=ioserver@forge.ipsl.jussieu.fr

files=$*

for file in $files 
do
  scp $file $forge_IP:$FORGE_DIR 
  ssh $forge_IP "chmod --quiet a+rw ${FORGE_DIR}/${file}"
done
